### ISSUE TITLE
VOTables in tours not loading in webclient

### ISSUE THREAD

**Issue by pkgw** [WorldWideTelescope/wwt-webgl-engine#182]
Reported by @astrodavid10. Example tour file:

https://data1.wwtassets.org/packages/2022/03_exoplanets/exoplanets_mar22.WTT

David reports that the data do show on the Windows client, although the coloring of the data points is missing due to WorldWideTelescope/wwt-windows-client#199.

**Comment by Carifio24** [comment]
I took a quick look at this while waiting for some jobs to run, and the reason that the layer doesn't show is that `VoTableLayer` isn't included in the switch [here](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/Layers/Layer.cs#L543). Adding it in will add display the layer. The colormap doesn't display, but that's because `VoTableLayer`s in the web engine don't seem to support colormaps. (Though neither `VoTableLayer` nor `SpreadSheetLayer` support group by values colormaps in the web engine, which this tour uses).

Also, FWIW, the colormap worked fine on my Windows client.

**Comment by pkgw** [comment]
OK, I think it makes the most sense to close this issue (as GitHub did automatically) since the basic issue should now be dealt with. It would be good to straighten out the colormap situation but that's a bigger thing to tackle.
