### ISSUE TITLE
Circle annotation radius

### ISSUE THREAD

**Issue by srcejon** [WorldWideTelescope/wwt-webgl-engine#297]
I've added a circle annotation with set_radius(5), which the [tutorial](https://docs.worldwidetelescope.org/webgl-reference/latest/tutorial/annotations/) suggests is in degrees.

However, here's what I get at different declinations:

![image](https://github.com/WorldWideTelescope/wwt-webgl-engine/assets/57259258/e2f0d51e-5e1a-4e62-8525-80d3df196fdc)

![image](https://github.com/WorldWideTelescope/wwt-webgl-engine/assets/57259258/112355aa-8152-423f-91a6-bf314bdbdaec)

Which doesn't seem correct. Am I missing something?

**Comment by pkgw** [comment]
You are not! The circle rendering code gets the sizes wrong and is lacking a cos(dec) term, which I discovered during an early WWT project. [At the time I applied a workaround][1] because the rendering engine code wasn't in a maintainable state. Nowadays, things are in much better shape and we can just fix the issue. Would you happen to be interested in preparing a pull request to do so?

[1]: https://github.com/starhunt-project/starhunt-web-client/blob/master/controllers/StarHuntController.js#L423-L431

**Comment by srcejon** [comment]
Thanks - I applied the same correction and the circle radius is now drawn as I'd expect.

> Would you happen to be interested in preparing a pull request to do so?

I'm not sure I know enough about it at the moment. Not sure where the 44 or 0.769 come from!

**Comment by srcejon** [comment]
Seems like circles can't be drawn at declination of 90 or -90 (even if we take care to avoid divide by zero).

**Comment by pkgw** [comment]
I've filed #299 to finally fix this bug. It's technically a breaking change, since it will alter what gets rendered by existing code that uses circle annotations, but we should be correct instead of wrong.

As for circles at ±90, yeah, I am not surprised that those locations fail. It might not be so hard to fix that, actually, since the rendering code is working with 3D vectors.
